[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false

[character]
error_symbol = "[â¯â¯â¯](bold red)"
success_symbol = "[â¯](bold red)[â¯](bold yellow)[â¯](bold green)"

[directory]
read_only = "ï€£ "
read_only_style = "red"

[git_branch]
symbol = "ïˆ "
style ='#a093c7'

[python]
symbol = "î˜† "
style = "yellow"
pyenv_prefix = "pyenv "
pyenv_version_name = true

[rlang]
symbol = "ï³’ "
style = "blue"
detect_extensions = ["R", "Rd", "Rmd", "Rproj", "Rsx"]
detect_files = []

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"
